### ISSUE TITLE
Update archlinux-keyring before installation

### ISSUE THREAD

**Issue by coxackie** [AnarchyLinux/anarchy-linux#854]
## Description

From past experience, it was frequent that the installation would fail because of non-updated keys. I would suggest running automatically `sudo pacman -Sy archlinux-keyring` before installation starts, so that this can be avoided. I had to do it manually a number of times.

A word of caution on this: it would not be recommended to do a full upgrade `sudo pacman -Syu`, as sometimes the medium will not have enough space for a full upgrade. This has happened to me, and it is why I am suggesting only updating `archlinux-keyring`.

**Comment by erazemkokot** [comment]
Fixed in #861.

**Comment by mgarbvs** [comment]
I was not able to install due to GPGME errors. I believe that this will fix this.

**Comment by erazemkokot** [comment]
@mgarbvs We'll generate a test iso hopefully today, then you can try it and if it works, we'll make a new release.

But in any case, since this has been merged to master, you can use "anarchy -u" (option 2 in the menu) to download the latest fixes. Try that and report back, please :)
