### ISSUE TITLE
openbox-themes (target not found)

### ISSUE THREAD

**Issue by frpenguin** [AnarchyLinux/anarchy-linux#860]
## Basic info:

**Anarchy version**: 1.0.5

**Installation method (VM/Host)**: VM (QEMU)

**System specifications (Processor, GPU, RAM ...)**: Ryzen 2700X

## What you expected would happen

Install anarchy with openbox

## What actually happened

The installer failed because it could not find the package 'openbox-themes'

## Steps needed to reproduce the bug

1. Start anarchy installer
2. Choose Anarchy-Advanced in Install System
2. In the Desktop Environment or Window Manager Section choose Anarchy-Openbox

## Extra info

![AnarchyLinux_Error](https://user-images.githubusercontent.com/53182405/65455848-c1b31600-de50-11e9-9276-af1ef39ac8c5.png)
## Possible fixes

openbox-themes is in the AUR

## Bug report checklist

* [x] I've checked for any existing issues similar to mine and tried the solutions provided there
* [x] I've checked online for any existing fixes to my issue and added the link above
* [x] I've tried taking logs and submitting them above

**Comment by condor2** [comment]
That package was moved to AUR. I have removed from the script.

**Comment by erazemkokot** [comment]
Cool, seems we can close this now :)
